/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package numero;

import java.awt.Color;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author ESFOT
 */
public class AdivinarNum extends javax.swing.JFrame {
    Random numAleatorio = new Random();
    int aleatorio = numAleatorio.nextInt(1000);
    /**
     * Creates new form AdivinarNum
     */
    public AdivinarNum() {
        initComponents();
        this.setTitle("Adivine el número entre 1 y 1000");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEnunciado = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        lblPista = new javax.swing.JLabel();
        lblIngre = new javax.swing.JLabel();
        btnNuevoJuego = new javax.swing.JButton();
        btnAdivinar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblEnunciado.setText("Tengo un número del 1 al 1000. ¿Puede usted adivinarlo?");

        lblNumero.setText("Número:");

        lblIngre.setText("Por favor, ingrese su primer intento.");

        btnNuevoJuego.setText("Jugar de Nuevo");
        btnNuevoJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoJuegoActionPerformed(evt);
            }
        });

        btnAdivinar.setText("Adivinar!");
        btnAdivinar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdivinarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdivinar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNuevoJuego))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPista, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEnunciado)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNumero)
                                .addGap(18, 18, 18)
                                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblIngre))
                        .addGap(0, 80, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEnunciado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIngre)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumero)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPista, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoJuego)
                    .addComponent(btnAdivinar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdivinarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdivinarActionPerformed
        String numero = txtNumero.getText();
        System.out.println(this.aleatorio);
        
        lblIngre.setText("");
        if(!numero.equals("")){//comprueba el numero si esta cerca a través de un rango{-100<x<100}
            if(Integer.parseInt(numero) >= (aleatorio - 100) && Integer.parseInt(numero) <= (aleatorio + 100)){
                this.getContentPane().setBackground(Color.RED);
            }else{
                this.getContentPane().setBackground(Color.BLUE);
            }
            if(Integer.parseInt(numero) < aleatorio){
                lblPista.setText("Demasiado bajo!");
                //this.getContentPane().setBackground(Color.RED);
            }else if (Integer.parseInt(numero) > aleatorio) {
                lblPista.setText("Demasiado alto!");
                //this.getContentPane().setBackground(Color.BLUE);
            }else{
                lblPista.setText("");
                JOptionPane.showMessageDialog(rootPane,"Correcto, ¡ADIVINASTE!");
                txtNumero.disable();
            }
        }else{
            JOptionPane.showMessageDialog(rootPane,"Ingrese algún número");
        }
    }//GEN-LAST:event_btnAdivinarActionPerformed

    private void btnNuevoJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoJuegoActionPerformed
        int mensaje = JOptionPane.showConfirmDialog(rootPane, "¿Está seguro?", "Jugar de Nuevo", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (mensaje == 0) {
            lblIngre.setText("Por favor, ingrese su primer intento");
            txtNumero.setText("");
            aleatorio = numAleatorio.nextInt(1000);
            txtNumero.enable();
        }

    }//GEN-LAST:event_btnNuevoJuegoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdivinarNum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdivinarNum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdivinarNum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdivinarNum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdivinarNum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdivinar;
    private javax.swing.JButton btnNuevoJuego;
    private javax.swing.JLabel lblEnunciado;
    private javax.swing.JLabel lblIngre;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblPista;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
